### PR TITLE
Fix(frontend): Error 404 page

### LINKED ISSUE #495: Error 404 page
- [x] Create copy
- [x] Create page
- [x] Apply to page
- [x] Change sizing of text below (reduce to 75%)

https://lifebank.io/not-found

@steph222 here is the copy:

"Uh-oh, we couldn't find the page you were looking for. Please, go back to the [home page](http://lifebank.io/) and try again. 

Remember that Lifebank is an open-source, self-managed project. However, if you have any specific questions to the team, please contact us through our [Telegram chat](https://t.me/eoscr) or contact the [EOS Costa Rica](https://eoscostarica.io/contact-us/) team directly."

### PR DESCRIPTION
**Pull request by steph222**
Resolves #495

### CODE REVIEW

**Review by Edgar097 — APPROVED** [review]

File: webapp/src/routes/NotFound/NotFound.js [hunk 1]
```diff
@@ -44,12 +51,18 @@ const useStyles = makeStyles((theme) => ({
     letterSpacing: "0.25px",
     textAlign: "center",
     color: "rgba(0, 0, 0, 0.6)",
-    marginBottom: 30
+    marginBottom: 30,
+    marginLeft: "10%",
+    marginRight: "10%"
+
```
Comment (tetogomez) [inline webapp/src/routes/NotFound/NotFound.js:57]: unnecessary blank space

**Review by tetogomez — CHANGES_REQUESTED** [review]
Please check the comment

File: webapp/src/routes/NotFound/NotFound.js (hunk 1 above)
Comment (steph222) [reply webapp/src/routes/NotFound/NotFound.js:57]: Thanks!!😊
