### PR TITLE
fix(frontend): Change textfield component 

### LINKED ISSUE #588: Change textfield component to buttons
Textfield is use as some kind of action selector but this component is not for that purpose.

- [x] Apply changes.
- [x] Check with @murillojorge appropriate UI for this action.
- [x] Add design changes to component according to conversation with Jorge
   - [x] Remove details
   - [x] Change action for icon "..." 
   - [x] Link filter - details 

Steps to test:
1. Sign in as Sponsor
2. Add an offer
3. Go to Offers Management

image

### PR DESCRIPTION
**Pull request by steph222**
Resolves #588 

### What does this PR do?
Change textfield component to buttons

### How should this be tested?
- Make run
- Go to Offers Management

before 
image

after
image

### CODE REVIEW

**Comment by steph222** [comment]
> @steph222 new component is still a Text Field or Select component, just changed the component design according to [this](https://material-ui.com/components/text-fields/).
> 
> Please, consider something like this [Menus](https://material-ui.com/components/menus/) or

I considered it and I did it, but due to the standard that is handled throughout the project when it comes to selecting an option, it is handled with select, so I saw better to follow the standard

But I don't know what you think is better

**Review by Edgar097 — COMMENTED** [review]
I think it would be better to make all the row linkable, its difficult to know that there is a feature in which you can see all the information of the offer, also the icon fo the actions, I thought that we were gonna change it to another one.

**Comment by steph222** [comment]
> I think it would be better to make all the row linkable, its difficult to know that there is a feature in which you can see all the information of the offer, also the icon for the actions, I thought that we were gonna change it to another one.

It is done according to Jorge's instructions

**Comment by leisterfrancisco** [comment]
@steph222 take a look a merge conflicts please

File: webapp/src/routes/OffersManagement/OffersManagement.js [hunk 1]
```diff
@@ -165,26 +162,39 @@ const OffersManagement = () => {
...
     }
   }
+
+  const [anchorEl, setAnchorEl] = useState(null)
+
+  const handleClick = (event) => {
+    setAnchorEl(event.currentTarget)
+  };
+
+  const handleClose1 = () => {
```
Comment (Edgar097) [inline webapp/src/routes/OffersManagement/OffersManagement.js:172]: Better not to tag functions with numbers, instead of "handleClose1" in my opinion is better like this "handleCloseMenu" or "handleClose" if it is global.

**Review by Edgar097 — APPROVED** [review]

File: webapp/src/language/es.json [hunk 2]
```diff
@@ -476,7 +476,7 @@
       "activate": "Activar",
       "active": "Activa",
       "inactive": "Inactiva",
-      "noProvidedDate": "Sin fecha",
+      "noProvidedDate": "*",
```
Comment (leisterfrancisco) [inline webapp/src/language/es.json:479]: add same symbol in spanish an english version for `noProvidedDate` tag

File: webapp/src/routes/OffersManagement/OffersManagement.js (hunk 1 above)
Comment (leisterfrancisco) [reply webapp/src/routes/OffersManagement/OffersManagement.js:172]: @steph222 take a look at Edgar suggestion

File: webapp/src/routes/OffersManagement/OffersManagement.js [hunk 3]
```diff
@@ -165,26 +162,39 @@ const OffersManagement = () => {
...
-        id="action-select"
+        open={Boolean(anchorEl)}
+        onClose={handleClose1}
       >
-        <MenuItem value="edit">{t('common.edit')}</MenuItem>
-        <MenuItem value="delete">{t('common.delete')}</MenuItem>
-        <MenuItem value={active ? 'deactivate' : 'activate'}>
+        <MenuItem onClick={(e) => handleActionClick("edit", active, offer_id)}>{t('common.edit')}</MenuItem>
+        <MenuItem onClick={(e) => handleActionClick("delete", active, offer_id)}>{t('common.delete')}</MenuItem>
+        <MenuItem onClick={(e) => handleActionClick(active ? 'deactivate' : 'activate', active, offer_id)}>
```
Comment (leisterfrancisco) [inline webapp/src/routes/OffersManagement/OffersManagement.js:191]: @steph222 is **_deactivate_** word right?

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]

File: webapp/src/routes/OffersManagement/OffersManagement.js (hunk 1 above)
Comment (steph222) [reply webapp/src/routes/OffersManagement/OffersManagement.js:172]: That was for the test, I forgot to change it

File: webapp/src/routes/OffersManagement/OffersManagement.js (hunk 3 above)
Comment (steph222) [reply webapp/src/routes/OffersManagement/OffersManagement.js:191]: It is the word that was implemented from the beginning  
image

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]
Remember to center the - symbol, It was a Jorge recommendation

image

File: webapp/src/routes/OffersManagement/OffersManagement.js [hunk 4]
```diff
@@ -165,26 +163,40 @@ const OffersManagement = () => {
...
+  };
+
   const Actions = (active, offer_id) => (
-    <FormControl variant="filled" className={classes.formControl}>
-      <InputLabel id="actions-selection-label">
-        {t('offersManagement.action')}
-      </InputLabel>
-      <Select
+    <div>
+      {console.log(offer_id)}
```
Comment (leisterfrancisco) [inline webapp/src/routes/OffersManagement/OffersManagement.js:179]: @steph222 is it necessary?

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]

**Review by leisterfrancisco — APPROVED** [review]
