### PR TITLE
fix(email bug): remove email from memory

### LINKED ISSUE #598: Accept not valid email
Sign up as sponsor, close session, sign up as sponsor, the before confirmation are still on memory, so the same mail can be use

### PR DESCRIPTION
**Pull request by Edgar097**
Resolves #598 

### What does this PR do?
Removes email data from memory

### How should this be tested?
- Make run
- Register a new user
- Try to register a new user with the same email

### CODE REVIEW

**Review by JustinCast — APPROVED** [review]

File: webapp/src/components/Signup/Signup.js [hunk 1]
```diff
@@ -434,6 +434,13 @@ const Signup = ({ isHome, isModal, isSideBar }) => {
 
   }, [errorpreRegisterLifebank])
 
+  useEffect(()=>{
+    if(open){
+      handleSetField('email', ' ')
+      setActiveStep(0)
+    }
+    },[open])
```
Comment (leisterfrancisco) [inline webapp/src/components/Signup/Signup.js:442]: add space after comma

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]

**Review by steph222 — APPROVED** [review]
