### PR TITLE
Fix/themes

### LINKED ISSUE #662: Themes

### PR DESCRIPTION
**Pull request by Edgar097**
Resolves #662 

### What does this PR do?
Move all styles from the routes to their own file

### How should this be tested?
- Make run
- Test the app
- Search for Design problems

### CODE REVIEW

**Comment by Edgar097** [comment]
This is the first step, please, if you find any design error, tell me to solve it in one go and continue with the part of the components that is more extensive @leisterfrancisco @steph222

**Review by JeanVegaD — APPROVED** [review]

**Comment by JeanVegaD** [comment]
> This is the first step, please, if you find any design error, tell me to solve it in one go and continue with the part of the components that is more extensive @leisterfrancisco @steph222
> 
> This can happen as it removes a lot of repeated code

File: webapp/src/routes/EditProfile/styles.js [hunk 1]
```diff
@@ -0,0 +1,217 @@
...
+    },
+  },
+  title: {
+    fontSize: 48,
+    marginBottom: theme.spacing(4)
+  },
+  rowBox: {
+    display: 'flex',
+    width: '100%',
+    justifyContent: 'space-between',
```
Comment (JustinCast) [inline webapp/src/routes/EditProfile/styles.js:22]: Why not to establish a global theme and have everything in common in just one place?. Instead of writing specific styles for each component. You know what I mean?

**Review by JustinCast — CHANGES_REQUESTED** [review]

File: webapp/src/routes/EditProfile/styles.js (hunk 1 above)
Comment (Edgar097) [reply webapp/src/routes/EditProfile/styles.js:22]: Yes, thats the goal, the problem is that there is a lot a code that we need to check. So in order for me to be more accurate and organize we are dividing this work in 3 steps. 
1. Add specific styles for each component since there are components that need that. (Routes) and remove duplicated code
2. Add specific styles for each component since there are components that need that. (Components) and remove duplicated code
3. Standarice certain styles for the whole app. Like the example you are pointing out

Comment (JustinCast) [reply webapp/src/routes/EditProfile/styles.js:22]: Ok, great!

**Review by leisterfrancisco — APPROVED** [review]

**Review by steph222 — APPROVED** [review]
