### PR TITLE
fix(frontend): fix notification time

### LINKED ISSUE #802: Problem when adding time to transfers

### PR DESCRIPTION
**Pull request by steph222**
Resolves #802 

### What does this PR do?
Fix notification time

### How should this be tested?
- Make run
- Open notifications
- See time

### CODE REVIEW

**Review by Edgar097 — APPROVED** [review]

File: webapp/src/components/NotificationStructure/NotificationStructure.js [hunk 1]
```diff
@@ -38,6 +37,11 @@ const NotificationStructure = ({ id, title, description, state, dateAndTime }) =
     response()
   }, [description])
 
+  useEffect(() => {
+    const hour = parseInt(dateAndTime.substring(11, 13)) - 6
+    setTime(hour.toString() + dateAndTime.substring(13, 19))
```
Comment (leisterfrancisco) [inline webapp/src/components/NotificationStructure/NotificationStructure.js:42]: @steph222  what if we handle dateAndTime as Date type, because the string format may change depending on the date format so if the manipulate the date as Date type when solved that possible problem.

Nota: Date type also provide the getDate, getMonth and other to get needed information. Take a look at [this](https://www.w3schools.com/js/js_date_methods.asp)

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]

File: webapp/src/components/NotificationStructure/NotificationStructure.js (hunk 1 above)
Comment (steph222) [reply webapp/src/components/NotificationStructure/NotificationStructure.js:42]: It was done that way because what is saved in the notification is a string, but of everything it contains, only two characters are needed, which are the hours, the rest is used normal.

Apply the change only in the notification

Comment (leisterfrancisco) [reply webapp/src/components/NotificationStructure/NotificationStructure.js:42]: @steph222 I suppose to, but in line 41, you are taking `dateAndTime.substring(11, 13)` that will really depend on the date format, despite of you need only one data from date I thing you should use that data in date format

**Review by leisterfrancisco — APPROVED** [review]
