### PR TITLE
fix(logout button)

### LINKED ISSUE #620: Sidebar logout section is not a button
Opening sidebar to logout, it isn't a button

Steps to test:
1. Sign in (any role)
2. Click sidebar

image

### PR DESCRIPTION
**Pull request by Edgar097**
Resolves #620 

### What does this PR do?
Log out is a button now

### How should this be tested?
- Make run
- Log In
- Log Out

### CODE REVIEW

**Review by steph222 — APPROVED** [review]

File: webapp/src/containers/SideBar.js [hunk 1]
```diff
@@ -104,9 +104,11 @@ const SideBar = ({ user, onLogout, triggerSideBarPosition }) => {
 
           <Box className={classes.optionLink} onClick={onLogout}>
             <LogoutIcon className={classes.iconOption} />
+            <Link to="/">
             <Typography variant="body1" className={classes.labelOption}>
               {t('logout')}
             </Typography>
```
Comment (leisterfrancisco) [inline webapp/src/containers/SideBar.js:110]: Please add indentation

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]

**Review by leisterfrancisco — APPROVED** [review]
