### PR TITLE
fix(fronted): add safe profile var query to avoid app crash

### LINKED ISSUE #600: App crashes when enter to profile without having accept the consent contract
When signing up as sponsor, the app crashes if the sponsor enter to the profile section and has had not accept consent contract.

Steps to test:
1. Don't accept the consent contract
2. Go to profile section
3. App crashes

### PR DESCRIPTION
**Pull request by leisterfrancisco**
Resolves #600 

### What does this PR do?
Add save profile variable query to avoid app crash when querying it

### How should this be tested?
- Make run
- Sign up as Sponsor
- Confirm Email
- Login as Sponsor
- Don't accept the consent contract
- Go to profile section
- Check that app doesn't crash

### CODE REVIEW

File: webapp/src/routes/Profile/ProfilePage.js [hunk 1]
```diff
@@ -133,6 +133,13 @@ const ProfilePage = () => {
     classes
   ])
 
+  useEffect(() => {
+    if (profile && !profile.consent) {
+      setMessegaAlert('Cannot edit your profile before you accept the consent contract')
```
Comment (leisterfrancisco) [inline webapp/src/routes/Profile/ProfilePage.js:138]: Pending to message to import from translation section

**Review by steph222 — APPROVED** [review]

**Review by Edgar097 — APPROVED** [review]
