### PR TITLE
Fix/edit sidebar

### LINKED ISSUE #721: Edit sidebar
- [x] Add tool section
- [ ] Add edit page
- [x] Add download report with download icon

### PR DESCRIPTION
**Pull request by leisterfrancisco**
Resolves #721 

### What does this PR do?
Move download report from topbar to sidebar

### How should this be tested?
- Make run
- Sign in as sponsor or lifebank
- Check exist a new tools section and download report work as supposed to be

### CODE REVIEW

File: webapp/src/containers/SideBar.js [hunk 1]
```diff
@@ -117,6 +124,30 @@ const SideBar = ({ user, onLogout, triggerSideBarPosition }) => {
...
       )}
+      {user && (user.role === 'lifebank' || user.role === 'sponsor') && 
+        <>
+          <Divider />
+          <Typography variant="body1" className={classes.infoLabel}>
+            {t('navigationDrawer.tools')}
+          </Typography>
+          <Box className={classes.optionLink} onClick={triggerSideBarPosition}>
+            <EditIcon className={classes.iconOption} />
+            <Link to="/">
```
Comment (leisterfrancisco) [inline webapp/src/containers/SideBar.js:135]: route is pending to future PR

**Review by steph222 — APPROVED** [review]
