### PR TITLE
fix(frontend): solve is define or is assigned but never use issues

### LINKED ISSUE #829: ES LINT Warnings
Lets fix these issues :

```
Compiled with warnings.

./src/components/MapShowOneLocation/index.js
  Line 100:6:  React Hook useEffect has a missing dependency: 'loadMarkersEvent'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/OfferView/OfferView.js
  Line 112:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array       react-hooks/exhaustive-deps
  Line 125:9:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

./src/components/DonationsDashboard/DonationsDashboard.js
  Line 124:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                                                                                                                                        react-hooks/exhaustive-deps
  Line 136:6:  React Hook useEffect has missing dependencies: 'handleOpen' and 't'. Either include them or remove the dependency array                                                                                                                     react-hooks/exhaustive-deps
  Line 147:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                                                                                                                                        react-hooks/exhaustive-deps
  Line 168:6:  React Hook useEffect has a missing dependency: 'role'. Either include it or remove the dependency array                                                                                                                                     react-hooks/exhaustive-deps
  Line 239:6:  React Hook useEffect has missing dependencies: 'donate', 'profile.name', 'role', and 't'. Either include them or remove the dependency array                                                                                                react-hooks/exhaustive-deps
  Line 251:8:  React Hook useEffect has an unnecessary dependency: 'scanValue'. Either exclude it or remove the dependency array. Outer scope values like 'scanValue' aren't valid dependencies because mutating them doesn't re-render the component      react-hooks/exhaustive-deps
  Line 427:8:  React Hook useEffect has an unnecessary dependency: 'openModalQR'. Either exclude it or remove the dependency array. Outer scope values like 'openModalQR' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps

./src/routes/EditProfile/EditProfile.js
  Line 128:6:  React Hook useEffect has missing dependencies: 'history' and 't'. Either include them or remove the dependency array       react-hooks/exhaustive-deps
  Line 139:6:  React Hook useEffect has missing dependencies: 'history' and 'logout'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 150:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                       react-hooks/exhaustive-deps

./src/components/MapPopup/index.js
  Line 143:16:  Assignments to the 'dd' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps

./src/components/VideoSection/VideoSection.js
  Line 16:5:  React Hook useEffect has a missing dependency: 'setVideoHeight'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/TransactionReport/TransactionReport.js
  Line 19:14:  'errroLoadProfile' is assigned a value but never used                                                                                                                                                                    no-unused-vars
  Line 19:74:  'client' is assigned a value but never used                                                                                                                                                                              no-unused-vars
  Line 33:7:   'errorReport' is assigned a value but never used                                                                                                                                                                         no-unused-vars
  Line 38:6:   React Hook useEffect has a missing dependency: 'loadProfile'. Either include it or remove the dependency array                                                                                                           react-hooks/exhaustive-deps
  Line 53:6:   React Hook useEffect has missing dependencies: 'currentUser', 'dateFrom', 'dateTo', 'formatDataToLifebankReport', 'formatDataToSponsorReport', and 'getReportQuery'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 113:6:  React Hook useEffect has a missing dependency: 'downloadReport'. Either include it or remove the dependency array                                                                                                        react-hooks/exhaustive-deps

./src/routes/OffersManagement/GenericOfferFormComponent.js
  Line 19:8:    'Checkbox' is defined but never used                                                                                                                                                                                                                          no-unused-vars
  Line 102:6:   React Hook useEffect has a missing dependency: 'setDates'. Either include it or remove the dependency array. If 'setDates' changes too often, find the parent component that defines it and wrap that definition in useCallback                               react-hooks/exhaustive-deps
  Line 150:10:  'openSnackbar' is assigned a value but never used                                                                                                                                                                                                             no-unused-vars
  Line 275:6:   React Hook useEffect has missing dependencies: 'setOffers', 't', and 'updatedOffer'. Either include them or remove the dependency array. If 'setOffers' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
  Line 286:6:   React Hook useEffect has missing dependencies: 'setOffers' and 't'. Either include them or remove the dependency array. If 'setOffers' changes too often, find the parent component that defines it and wrap that definition in useCallback                   react-hooks/exhaustive-deps
  Line 369:89:  Comments inside children section of tag should be placed inside braces                                                                                                                                                                                        react/jsx-no-comment-textnodes
  Line 371:77:  Comments inside children section of tag should be placed inside braces                                                                                                                                                                                        react/jsx-no-comment-textnodes

./src/components/ViewSchedule/ViewSchedule.js
  Line 20:31:  Function declared in a loop contains unsafe references to variable(s) 'schedule', 'schedule', 'schedule'  no-loop-func

./src/components/Signup/Signup.js
  Line 234:6:  React Hook useEffect has a missing dependency: 'user'. Either include it or remove the dependency array                                   react-hooks/exhaustive-deps
  Line 234:7:  React Hook useEffect has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked  react-hooks/exhaustive-deps
  Line 246:6:  React Hook useEffect has missing dependencies: 'handleOpen' and 't'. Either include them or remove the dependency array                   react-hooks/exhaustive-deps
  Line 258:6:  React Hook useEffect has missing dependencies: 'handleOpen' and 't'. Either include them or remove the dependency array                   react-hooks/exhaustive-deps
  Line 271:6:  React Hook useEffect has missing dependencies: 'handleOpen', 'login', and 't'. Either include them or remove the dependency array         react-hooks/exhaustive-deps
  Line 281:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                                      react-hooks/exhaustive-deps
  Line 290:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                                      react-hooks/exhaustive-deps
  Line 299:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                                      react-hooks/exhaustive-deps
  Line 306:6:  React Hook useEffect has a missing dependency: 'handleSetField'. Either include it or remove the dependency array                         react-hooks/exhaustive-deps

./src/components/Notification/Notification.js
  Line 29:10:  'element' is defined but never used                      no-unused-vars
  Line 72:18:  'errorNotifications' is assigned a value but never used  no-unused-vars

./src/routes/Home/HomeDesktop.js
  Line 2:10:  'useMutation' is defined but never used                                                                                                                                                                                                                                                                     no-unused-vars
  Line 49:6:  React Hook useEffect has a missing dependency: 'props'. Either include it or remove the dependency array. However, 'props' will change when *any* prop changes, so the preferred fix is to destructure the 'props' object outside of the useEffect call and refer to those specific props inside useEffect  react-hooks/exhaustive-deps

./src/routes/HistoryDashboard/HistoryDashboard.js
  Line 2:22:   'useTheme' is defined but never used                                                                                                                                                     no-unused-vars
  Line 34:5:   'loadProfile' is assigned a value but never used                                                                                                                                         no-unused-vars
  Line 35:14:  'errroLoadProfile' is assigned a value but never used                                                                                                                                    no-unused-vars
  Line 35:51:  'profile' is assigned a value but never used                                                                                                                                             no-unused-vars
  Line 35:74:  'client' is assigned a value but never used                                                                                                                                              no-unused-vars
  Line 40:7:   'errorReport' is assigned a value but never used                                                                                                                                         no-unused-vars
  Line 48:23:  Unexpected mix of '&&' and '||'                                                                                                                                                          no-mixed-operators
  Line 48:58:  Unexpected mix of '&&' and '||'                                                                                                                                                          no-mixed-operators
  Line 53:6:   React Hook useEffect has missing dependencies: 'currentUser', 'formatDataToDonorReport', 'formatDataToReport', and 'getReportQuery'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/MapShowLocations/index.js
  Line 320:6:  React Hook useEffect has missing dependencies: 'loadMarkersEvent' and 't'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/routes/OffersManagement/OffersManagement.js
  Line 33:10:  'TextField' is defined but never used                                                                                no-unused-vars
  Line 273:6:  React Hook useEffect has missing dependencies: 'offers' and 't'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/LanguageSelector/LanguageSelector.js
  Line 33:25:  'login' is assigned a value but never used  no-unused-vars

./src/routes/EmailVerification/EmailVerification.js
  Line 38:6:  React Hook useEffect has a missing dependency: 'verifyEmail'. Either include it or remove the dependency array                                     react-hooks/exhaustive-deps
  Line 60:6:  React Hook useEffect has missing dependencies: 'code', 'history', 'logout', and 'verifyEmail'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/CredentialsRecovery/CredentialsRecovery.js
  Line 3:22:   'useTheme' is defined but never used                                                                                       no-unused-vars
  Line 85:6:   React Hook useEffect has a missing dependency: 'getAccountSignupMethod'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 111:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                       react-hooks/exhaustive-deps

./src/components/Signup/SignupDonor.js
  Line 40:6:  React Hook useEffect has a missing dependency: '***'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/MapEditLocation/index.js
  Line 41:18:  Assignments to the 'markerNode' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps
  Line 44:14:  Assignments to the 'marker' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect      react-hooks/exhaustive-deps

./src/routes/InfoPage/InfoPageDesktop.js
  Line 4:8:    'Slider' is defined but never used                                                                                                                                                               no-unused-vars
  Line 82:6:   React Hook useEffect has a missing dependency: 'loadingDataOffer'. Either include it or remove the dependency array                                                                              react-hooks/exhaustive-deps
  Line 99:6:   React Hook useEffect has missing dependencies: 'getInfo', 'getOffers', and 'profile'. Either include them or remove the dependency array                                                         react-hooks/exhaustive-deps
  Line 121:6:  React Hook useEffect has missing dependencies: 'getInfo', 'getOffers', 'history', 'location.state.profile.account', 'logout', and 'profile'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/LoginModal/Login.js
  Line 50:10:   'changePassword' is assigned a value but never used                                                                                         no-unused-vars
  Line 50:26:   'setChangePassword' is assigned a value but never used                                                                                      no-unused-vars
  Line 64:14:   'errorCheckEmailVerified' is assigned a value but never used                                                                                no-unused-vars
  Line 65:16:   'checkEmailVerifiedLoading' is assigned a value but never used                                                                              no-unused-vars
  Line 73:14:   'errorSendEmail' is assigned a value but never used                                                                                         no-unused-vars
  Line 74:16:   'SendEmailLoading' is assigned a value but never used                                                                                       no-unused-vars
  Line 108:20:  'checkEmail' is assigned a value but never used                                                                                             no-unused-vars
  Line 115:20:  'getHash' is assigned a value but never used                                                                                                no-unused-vars
  Line 184:6:   React Hook useEffect has missing dependencies: 'checkEmailVerified' and 'user.account'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 191:6:   React Hook useEffect has a missing dependency: 'login'. Either include it or remove the dependency array                                    react-hooks/exhaustive-deps

./src/components/Nearby/Nerby.js
  Line 51:6:  React Hook useEffect has a missing dependency: 'getNerbyLocations'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/SearchComponent/SeachComponent.js
  Line 59:6:  React Hook useEffect has a missing dependency: 'props'. Either include it or remove the dependency array. However, 'props' will change when *any* prop changes, so the preferred fix is to destructure the 'props' object outside of the useEffect call and refer to those specific props inside useEffect  react-hooks/exhaustive-deps

./src/routes/RegisterLifebank/RegisterLifebank.js
  Line 62:6:   React Hook useEffect has a missing dependency: 'verifyEmail'. Either include it or remove the dependency array                                     react-hooks/exhaustive-deps
  Line 72:6:   React Hook useEffect has a missing dependency: 'handleCreateAccountLifebank'. Either include it or remove the dependency array                     react-hooks/exhaustive-deps
  Line 89:6:   React Hook useEffect has missing dependencies: 'code', 'history', 'logout', and 'verifyEmail'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 106:6:  React Hook useEffect has missing dependencies: 'code', 'history', 'logout', and 'verifyEmail'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/NotificationStructure/NotificationStructure.js
  Line 6:10:   'useTranslation' is defined but never used                                                                  no-unused-vars
  Line 8:8:    'OldNotificationIcon' is defined but never used                                                             no-unused-vars
  Line 30:14:  'errorEditResults' is assigned a value but never used                                                       no-unused-vars
  Line 30:41:  'editLoading' is assigned a value but never used                                                            no-unused-vars
  Line 30:83:  'editNotificationStateResult' is assigned a value but never used                                            no-unused-vars
  Line 39:6:   React Hook useEffect has a missing dependency: 'getData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/Settings/Settings.js
  Line 72:14:   'errorUpdateEmailSubscription' is assigned a value but never used                                                          no-unused-vars
  Line 72:53:   'updateEmailSubscriptionLoading' is assigned a value but never used                                                        no-unused-vars
  Line 130:12:  Unexpected use of comma operator                                                                                           no-sequences
  Line 152:6:   React Hook useEffect has a missing dependency: 'loadProfile'. Either include it or remove the dependency array             react-hooks/exhaustive-deps
  Line 177:6:   React Hook useEffect has missing dependencies: 'loadProfile' and 't'. Either include them or remove the dependency array   react-hooks/exhaustive-deps
  Line 194:6:   React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                       react-hooks/exhaustive-deps
  Line 228:6:   React Hook useEffect has a missing dependency: 'getAccountSignupMethod'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/ConsetComponent/ConsentComponent.js
  Line 72:6:   React Hook useEffect has a missing dependency: 'loadProfile'. Either include it or remove the dependency array                               react-hooks/exhaustive-deps
  Line 76:6:   React Hook useEffect has missing dependencies: 'currentUser' and 'handleOpenConsent'. Either include them or remove the dependency array     react-hooks/exhaustive-deps
  Line 95:6:   React Hook useEffect has missing dependencies: 'profile.role', 't', and 'updateProfile'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 105:6:  React Hook useEffect has a missing dependency: 't'. Either include it or remove the dependency array                                         react-hooks/exhaustive-deps

./src/components/Signup/SignupSponsor/SimpleRegisterForm.js
  Line 74:6:  React Hook useEffect has a missing dependency: '***'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/routes/Profile/ProfilePageSponsor.js
  Line 76:6:    React Hook useEffect has missing dependencies: 'getData' and 'profile.account'. Either include them or remove the dependency array       react-hooks/exhaustive-deps
  Line 85:6:    React Hook useEffect has missing dependencies: 'history' and 'logout'. Either include them or remove the dependency array                react-hooks/exhaustive-deps
  Line 131:6:   React Hook useEffect has a missing dependency: 'checkAvailableFields'. Either include it or remove the dependency array                  react-hooks/exhaustive-deps
  Line 142:6:   React Hook useEffect has missing dependencies: 'history', 'location.state', and 't'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 361:15:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                jsx-a11y/alt-text

./src/routes/EditProfile/EditProfileBank.js
  Line 78:5:    React Hook useCallback has a missing dependency: 'handleSetField'. Either include it or remove the dependency array                                                                                                                                                                      react-hooks/exhaustive-deps
  Line 126:31:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                 react-hooks/exhaustive-deps
  Line 130:33:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                 react-hooks/exhaustive-deps
  Line 152:6:   React Hook useEffect has missing dependencies: 'isValid', 'onSubmit', 'profile.account', 'user', and 'username'. Either include them or remove the dependency array. If 'onSubmit' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
  Line 162:6:   React Hook useEffect has a missing dependency: 'user'. Either include it or remove the dependency array. You can also do a functional update 'setUser(u => ...)' if you only need 'user' in the 'setUser' call                                                                           react-hooks/exhaustive-deps
  Line 535:19:  No duplicate props allowed                                                                                                                                                                                                                                                               react/jsx-no-duplicate-props

./src/routes/EditProfile/EditProfileBankMobile.js
  Line 78:5:    React Hook useCallback has a missing dependency: 'handleSetField'. Either include it or remove the dependency array                                                                                                                                                                      react-hooks/exhaustive-deps
  Line 138:5:   React Hook useCallback has a missing dependency: 'handleSetField'. Either include it or remove the dependency array                                                                                                                                                                      react-hooks/exhaustive-deps
  Line 143:5:   React Hook useCallback has a missing dependency: 'handleSetField'. Either include it or remove the dependency array                                                                                                                                                                      react-hooks/exhaustive-deps
  Line 164:6:   React Hook useEffect has missing dependencies: 'isValid', 'onSubmit', 'profile.account', 'user', and 'username'. Either include them or remove the dependency array. If 'onSubmit' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
  Line 174:6:   React Hook useEffect has a missing dependency: 'user'. Either include it or remove the dependency array. You can also do a functional update 'setUser(u => ...)' if you only need 'user' in the 'setUser' call                                                                           react-hooks/exhaustive-deps
  Line 525:15:  No duplicate props allowed                                                                                                                                                                                                                                                               react/jsx-no-duplicate-props

./src/routes/Profile/ProfilePageDonor.js
  Line 82:6:  React Hook useEffect has missing dependencies: 'history', 'location.state', and 't'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/routes/OffersApproval/OffersApproval.js
  Line 84:6:    React Hook useEffect has a missing dependency: 'loadingInfo'. Either include it or remove the dependency array                react-hooks/exhaustive-deps
  Line 92:6:    React Hook useEffect has a missing dependency: 'loadingDataOffer'. Either include it or remove the dependency array           react-hooks/exhaustive-deps
  Line 97:6:    React Hook useEffect has missing dependencies: 'getInfo' and 'getOffers'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 106:24:  Expected to return a value in arrow function                                                                                  array-callback-return
  Line 107:7:   Expected a default case                                                                                                       default-case

./src/routes/Profile/ProfilePageLifebank.js
  Line 84:6:    React Hook useEffect has missing dependencies: 'history' and 'logout'. Either include them or remove the dependency array                react-hooks/exhaustive-deps
  Line 131:6:   React Hook useEffect has a missing dependency: 'checkAvailableFields'. Either include it or remove the dependency array                  react-hooks/exhaustive-deps
  Line 142:6:   React Hook useEffect has missing dependencies: 'history', 'location.state', and 't'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 350:15:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                jsx-a11y/alt-text

./src/routes/EditProfile/EditProfileSponsorMobile.js
  Line 89:5:   React Hook useMemo has a missing dependency: 'values'. Either include it or remove the dependency array. You can also do a functional update 'setValues(v => ...)' if you only need 'values' in the 'setValues' call  react-hooks/exhaustive-deps
  Line 94:5:   React Hook useCallback has an unnecessary dependency: 'user.geolocation'. Either exclude it or remove the dependency array                                                                                            react-hooks/exhaustive-deps
  Line 102:5:  React Hook useMemo has an unnecessary dependency: 'user.schedule'. Either exclude it or remove the dependency array                                                                                                   react-hooks/exhaustive-deps
  Line 175:6:  React Hook useEffect has a missing dependency: 'addAddress'. Either include it or remove the dependency array                                                                                                         react-hooks/exhaustive-deps
  Line 185:6:  React Hook useEffect has a missing dependency: 'user'. Either include it or remove the dependency array. You can also do a functional update 'setUser(u => ...)' if you only need 'user' in the 'setUser' call        react-hooks/exhaustive-deps

./src/routes/EditProfile/EditProfileSponsor.js
  Line 90:5:   React Hook useMemo has a missing dependency: 'values'. Either include it or remove the dependency array. You can also do a functional update 'setValues(v => ...)' if you only need 'values' in the 'setValues' call  react-hooks/exhaustive-deps
  Line 95:5:   React Hook useCallback has an unnecessary dependency: 'user.geolocation'. Either exclude it or remove the dependency array                                                                                            react-hooks/exhaustive-deps
  Line 103:5:  React Hook useMemo has an unnecessary dependency: 'user.schedule'. Either exclude it or remove the dependency array                                                                                                   react-hooks/exhaustive-deps
  Line 174:6:  React Hook useEffect has a missing dependency: 'addAddress'. Either include it or remove the dependency array                                                                                                         react-hooks/exhaustive-deps
  Line 184:6:  React Hook useEffect has a missing dependency: 'user'. Either include it or remove the dependency array. You can also do a functional update 'setUser(u => ...)' if you only need 'user' in the 'setUser' call        react-hooks/exhaustive-deps

./src/routes/Home/Home.js
  Line 94:6:   React Hook useEffect has missing dependencies: 'fetchError' and 'typeError'. Either include them or remove the dependency array                                                                  react-hooks/exhaustive-deps
  Line 135:6:  React Hook useEffect has missing dependencies: 'loadingDataOffer', 'searchValue', 'valueOfferCat', 'valueSponsorCat', and 'valueTokenPrice'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 154:6:  React Hook useEffect has missing dependencies: 'loadingDataBanks' and 'searchValue'. Either include them or remove the dependency array                                                          react-hooks/exhaustive-deps
  Line 180:6:  React Hook useEffect has missing dependencies: 'loadingDataSpons', 'searchValue', and 'valueSponsorCat'. Either include them or remove the dependency array                                      react-hooks/exhaustive-deps
  Line 192:6:  React Hook useEffect has missing dependencies: 'getLifebanks', 'getOffers', and 'getSponsors'. Either include them or remove the dependency array                                                react-hooks/exhaustive-deps

./src/routes/InfoPage/InfoPageMobile.js
  Line 95:6:   React Hook useEffect has a missing dependency: 'getInfo'. Either include it or remove the dependency array                                                                                       react-hooks/exhaustive-deps
  Line 185:6:  React Hook useEffect has a missing dependency: 'loadingDataOffer'. Either include it or remove the dependency array                                                                              react-hooks/exhaustive-deps
  Line 202:6:  React Hook useEffect has missing dependencies: 'getInfo', 'getOffers', and 'profile'. Either include them or remove the dependency array                                                         react-hooks/exhaustive-deps
  Line 224:6:  React Hook useEffect has missing dependencies: 'getInfo', 'getOffers', 'history', 'location.state.profile.account', 'logout', and 'profile'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/routes/Profile/ProfilePage.js
  Line 96:6:   React Hook useEffect has missing dependencies: 'handleOpenAlert' and 't'. Either include them or remove the dependency array                        react-hooks/exhaustive-deps
  Line 110:6:  React Hook useEffect has missing dependencies: 'handleOpenAlert' and 't'. Either include them or remove the dependency array                        react-hooks/exhaustive-deps
  Line 120:6:  React Hook useEffect has missing dependencies: 'history' and 'logout'. Either include them or remove the dependency array                           react-hooks/exhaustive-deps
  Line 134:6:  React Hook useEffect has missing dependencies: 'handleOpenAlert', 'history', 'logout', and 't'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 148:6:  React Hook useEffect has missing dependencies: 'handleOpenAlert', 'history', 'logout', and 't'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

### LINKED ISSUE #838: ES LINT: Remove unused variables
Dep: #829

### PR DESCRIPTION
**Pull request by leisterfrancisco**
Resolves #838 

### What does this PR do?
Solve is defined or is assigned but never use issues

### How should this be tested?
- Make run
- Check there is no console log errors with defined or assigned status

### CODE REVIEW

File: webapp/src/routes/EditProfile/EditProfileBankMobile.js [hunk 1]
```diff
@@ -522,7 +522,6 @@ const EditProfileBankMobile = ({ profile, onSubmit, setField, loading, userName
               InputLabelProps={{
                 shrink: true
               }}
-              className={classes.textField}
```
Comment (leisterfrancisco) [inline webapp/src/routes/EditProfile/EditProfileBankMobile.js:525]: @Edgar097 could you please check if this no cause any problem, the thing is that there was two `className `declaration to same component.

**Review by steph222 — APPROVED** [review]
