### PR TITLE
fix(frontend): add visibility to password field

### LINKED ISSUE #611: Password Recovery Credential field are not of password type
Password field are not of password type, so, anyone near of me could see my new password.

- [ ] Research other apps
- [ ] Change to password type hiding typed letter as * and adding option to see it (eye icon).
- [ ]  Add a space to retype password as confirmation.

Steps to test:
1. Go to Credential Recovery
2. Type something in password section
3. See what you type

More about: https://ux.stackexchange.com/questions/20953/why-should-we-ask-the-password-twice-during-registration

image

### PR DESCRIPTION
**Pull request by leisterfrancisco**
Resolves #611 

### What does this PR do?
Add toggle visibility to password field

### How should this be tested?
- Make run
- Go to Credential Recovery
- Type something in password section
- Toggle the eye button

### CODE REVIEW

File: webapp/src/components/CredentialsRecovery/CredentialsRecovery.js [hunk 1]
```diff
@@ -118,7 +122,7 @@ const CredentialsRecovery = ({ overrideBoxClass, overrideLabelClass }) => {
 
   const [
     getAccountSignupMethod,
-    { error: errorGetAccountSignupMethod, loading: getAccountSignupMethodLoading, data: { signup_method: getAccountSignupMethodResult } = {} }
```
Comment (leisterfrancisco) [inline webapp/src/components/CredentialsRecovery/CredentialsRecovery.js:121]: Those variables are not in use

**Review by steph222 — APPROVED** [review]

**Review by Edgar097 — APPROVED** [review]
