### PR TITLE
Fix/update sponsor profile bug

### LINKED ISSUE #366: Update ProfilePageSponsor bug

### PR DESCRIPTION
**Pull request by JustinCast**
# Fix Sponsor's complete profile functionality
This PR provides a fix for an unexpected behavior when completing the sponsor profile
# How this should be tested?
- `make run`
- Go to `localhost:3000`
- Create a new sponsor
- Go and complete the fields
- Save the changes
# Linked issues
closes #366

### CODE REVIEW

File: webapp/src/routes/EditProfile/EditProfileSponsor.js [hunk 1]
```diff
@@ -22,7 +22,8 @@ import TwitterIcon from '../../assets/twitter.svg'
 import MapEditLocation from '../../components/MapEditLocation'
 import Carousel from '../../components/Carousel'
 import Schedule from '../../components/Schedule'
-import Logo from '../../components/Logo'
+//import Logo from '../../components/Logo'
```
Comment (AngeloCG97) [inline webapp/src/routes/EditProfile/EditProfileSponsor.js:25]: review this comment

Comment (JustinCast) [reply webapp/src/routes/EditProfile/EditProfileSponsor.js:25]: Fixed it!

**Review by JeanVegaD — CHANGES_REQUESTED** [review]
edit profile doesn't allow update location

**Review by JeanVegaD — APPROVED** [review]

**Review by AngeloCG97 — APPROVED** [review]
