### PR TITLE
fix(close menu): close menu when option is click

### LINKED ISSUE #535: Close sidebar when option is click
image

### PR DESCRIPTION
**Pull request by Edgar097**
Resolves #535 

image

### CODE REVIEW

**Review by leisterfrancisco — APPROVED** [review]
Nice 👍

File: webapp/src/containers/SideBar.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ const SideBar = ({ user, onLogout, triggerSideBarPosition }) => {
       <Box className={classes.optionLink}>
         <LoginModal isSideBar />
       </Box>
-      <Box className={classes.optionLink}>
+      <Box className={classes.optionLink} onClick={() => triggerSideBarPosition()}>
```
Comment (JustinCast) [inline webapp/src/containers/SideBar.js:69]: What if we use `onClick={triggerSideBarPosition}`, since that function calling doesn't have any parameter

File: webapp/src/containers/SideBar.js [hunk 2]
```diff
@@ -84,7 +84,7 @@ const SideBar = ({ user, onLogout, triggerSideBarPosition }) => {
       {user && (
         <>
           {user.role === 'sponsor' && (
-            <Box className={classes.optionLink}>
+            <Box className={classes.optionLink} onClick={() => triggerSideBarPosition()}>
```
Comment (JustinCast) [inline webapp/src/containers/SideBar.js:87]: Same here

File: webapp/src/containers/SideBar.js [hunk 3]
```diff
@@ -93,7 +93,7 @@ const SideBar = ({ user, onLogout, triggerSideBarPosition }) => {
               </Link>
             </Box>
           )}
-          <Box className={classes.optionLink}>
+          <Box className={classes.optionLink} onClick={() => triggerSideBarPosition()}>
```
Comment (JustinCast) [inline webapp/src/containers/SideBar.js:96]: Same here

**Review by tetogomez — APPROVED** [review]
LGTM

**Review by steph222 — APPROVED** [review]
Good Work!

**Review by JustinCast — APPROVED** [review]
