### PR TITLE
 Bugs found by codefactor fixed

### LINKED ISSUE #189: Fix 'Identifier &#39;has_immunity_test&#39; is not in camel case.' issue in hapi\src\utils\lifebankcode.js
[CodeFactor](https://www.codefactor.io/repository/github/eoscostarica/lifebank) found an issue: Identifier &#39;has_immunity_test&#39; is not in camel case.

It's currently on:
[hapi\src\utils\lifebankcode.js:32
](https://www.codefactor.io/repository/github/eoscostarica/lifebank/source/master/hapi/src/utils/lifebankcode.js#L32)

### PR DESCRIPTION
**Pull request by JustinCast**
# Fixing bugs found by code factor.  
- If you want a full detailed description, just go to the codefactor [project](https://www.codefactor.io/repository/github/eoscostarica/lifebank).

### Linked issues
- Closes #189 #192 #190 #194 #195 #196 #197 #198 #199

### CODE REVIEW

File: hapi/src/utils/lifebankcode.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ const addLifebank = (
         data: {
           account,
           lifebank_name: name,
-          has_immunity_test: has_immunity_test || false,
+          hasImmunityTest: hasImmunityTest || false,
```
Comment (adriexnet) [inline hapi/src/utils/lifebankcode.js:48]: @JustinCast the smart contract action expect "has_immunity_test" not "hasImmunityTest" https://jungle3.bloks.io/account/lifebankcode?loadContract=true&tab=Actions&account=lifebankcode&scope=lifebankcode&limit=100&table=lifebanks&action=addlifebank if you want to fix a linter warning related to snake case the proper way will be `has_immunity_test: hasImmunityTest || false,` so that the smart contract get the value with the propper key because `hasImmunityTest` will be ignored because it's no registered in the action

File: hapi/src/utils/lifebankcode.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ const addDonor = (account, password) => {
 const addLifebank = (
   account,
   password,
-  { name, has_immunity_test, geolocation, ...profile }
+  { name, hasImmunityTest, geolocation, ...profile }
```
Comment (adriexnet) [inline hapi/src/utils/lifebankcode.js:32]: @JustinCast the FE will send `has_immunity_test` https://github.com/eoscostarica/lifebank/blob/9c84bb7113a9ec226113f103b038ba1285a4cb02/webapp/src/routes/Signup/SignupLifeBank.js#L184 so if you are using a destructuring with `hasImmunityTest ` always will be undefined if you are trying to fix a warning related to snake_case you should use `has_immunity_test : hasImmunityTest`

File: hapi/src/utils/lifebankcode.js [hunk 3]
```diff
@@ -60,7 +60,7 @@ const addLifebank = (
 const upLifebank = (
   account,
   password,
-  { name, has_immunity_test, geolocation, ...profile }
+  { name, hasImmunityTest, geolocation, ...profile }
```
Comment (adriexnet) [inline hapi/src/utils/lifebankcode.js:63]: same problem here, the FE will send `has_immunity_test` so you should use `has_immunity_test: hasImmunityTest `

File: hapi/src/utils/lifebankcode.js [hunk 4]
```diff
@@ -76,7 +76,7 @@ const upLifebank = (
         data: {
           account,
           lifebank_name: name,
-          has_immunity_test: has_immunity_test || false,
+          hasImmunityTest: hasImmunityTest || false,
```
Comment (adriexnet) [inline hapi/src/utils/lifebankcode.js:79]: same here, the smart contract expect `has_immunity_test` not `hasImmunityTest` so you should use `has_immunity_test: hasImmunityTest || false,`

File: webapp/public/index.html [hunk 5]
```diff
@@ -62,17 +52,18 @@
       work correctly both with client-side routing and a non-root public URL.
       Learn how to configure a non-root public URL by running `npm run build`.
     -->
-    <title>
-      Give blood banks a lifeline. Register to donate life and get rewards from
```
Comment (adriexnet) [inline webapp/public/index.html:66]: @JustinCast are you using prettier to ident this file? just to confirm

File: wallet/Dockerfile [hunk 6]
```diff
@@ -8,7 +8,8 @@ RUN apt-get update && apt-get install -y wget
 
 # Install EOSIO
 RUN wget -O eosio.deb $EOSIO_PACKAGE_URL
-RUN apt-get install -y /eosio.deb
+RUN apt-get install -y /eosio.deb --no-install-recommends && apt-get clean \
```
Comment (adriexnet) [inline wallet/Dockerfile:11]: @JustinCast the make run it's still working after add this change? could you remove your local container and run `make run` from the scratch? just to confirm that the wallet it's still running

Comment (JustinCast) [reply wallet/Dockerfile:11]: Yep, it's still running

File: webapp/public/index.html (hunk 5 above)
Comment (JustinCast) [reply webapp/public/index.html:66]: Yes. Prettier with the included config in the repo.
